nome = input('digite algo >>>')
print('o tipo primitivo e', type(nome))
print('so tem espaços',nome.isspace())
print('so tem numero',nome.isnumeric())
print('e alfabetico',nome.isalpha())
print('e alphanumerico',nome.isalnum())
print('esta em maiuscula',nome.isupper())
print('esta em minusculor',nome.islower())
print('esta capitalizado',nome.capitalize())
